### ISSUE TITLE
Being able to finish a task and claim payout

### ISSUE THREAD

**Issue by JingyuZ** [colonyportal/colonyPortal#21]
I read white paper really quick trying to find the corresponding content, but I think reading colony JS API is better to understand the flow.

Here are the steps I think we need to include to finish a task:
1. `getTaskPayout.call({ taskId, role, token })` can give us how many tokens will be paid to corresponding roles (evaluator, manager, worker). I'm thinking we can show this in task details/task index page.
2. `finalizeTask.send({ taskId }, options)`: finalize a task so that no further changes are allowed to task
3. `submitTaskDeliverable.send({ taskId, deliverableHash }, options)`,  i.e. the output of the work performed for task
4. `claimPayout.send({ taskId, role, token }, options)`:
Claims the payout for token denomination for work completed in task `taskId` by contributor with role `role`. This step has to happen after the task is finalized.

**Comment by sogasg** [comment]
I created issues for 1 and 2 since they should be in the MVP. So that the work can be divided.

1: #23, #24 
2: #25, #26

**Comment by JordanEllis6809** [comment]
I create issues for 3 and 4, which are placed in the backlog since we won't get to it for MVP.

3. https://github.com/colonyportal/colonyPortal/issues/30 , https://github.com/colonyportal/colonyPortal/issues/31 
4. https://github.com/colonyportal/colonyPortal/issues/32 , https://github.com/colonyportal/colonyPortal/issues/33

**Comment by JordanEllis6809** [comment]
This has been broken down into individual tasks. Closing this now.
